name: Run ESLint

on:
  pull_request:
    branches: [ master ]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install
      - name: eslint
        run: npm run lint
